### ISSUE TITLE
JwtUtils.validateIdToken() is always false

### ISSUE THREAD

**Issue by mbe14** [XeroAPI/xero-netstandard-oauth2-app#4]
I've set-up a Test Company in Xero, got the clientId and secret stored in the `appSettings.json` file. Also the CallBackUri matches the one from the Xero Developer App page.
However, in the `Callback` method from the `Authorization` controller, this expression always evaluates to false:
`if (!JwtUtils.validateIdToken(xeroToken.IdToken, XeroConfig.Value.ClientId))
return Content("ID token is not valid");`
If I comment out the IdToken validation, I get the proper list of tenants from `List<Tenant> tenants = await client.GetConnectionsAsync(xeroToken);` meaning that the authorization was successful. 
Once I get the tenants, I can successfully call any method from let's say `AccountingApi`.
If the authorization is successful, why is the `JwtUtils.validateIdToken()` always false?

**Comment by aakashpolra** [comment]
Hi Mihai,
Hopefully this PR helps:
https://github.com/XeroAPI/xero-netstandard-oauth2-app/pull/5

**Comment by shainegordon** [comment]
I have the same issue.

This is caused by a misconfigured "issuer" string in JwtUtils.

```
string str = "http://identity.xero.com";
...
validationParameters.ValidIssuer = str;
```

the problem here is that the issuer on the JWT is `https://identity.xero.com` (notice the HTTPS)

**Comment by rlayhbrian** [comment]
Appears to have been commented out to run with the latest SDK
